pool: 
   vmImage: ubuntu-latest

pr:
- master
- main
- releases/*

jobs:
- job: waitForValidation
  displayName: Wait for external validation  
  pool: server    
  timeoutInMinutes: 10
  steps:   
  - task: queryWorkItems@0
    inputs:
      queryId: 
      #maxThreshold: '0' 
      #minThreshold: '0' 