---
    - hosts: all
      become: true

      tasks:
        - name: Creates directory
          file:
            path: /media/Intranet-of-Things
            state: directory
            owner: malinka
            group: malinka

        - name: Install package for NTFS partition
          apt:
            pkg:
              - ntfs-3g
            state: latest
            update_cache: true

        - name: Mount USB disk
          mount:
            path: /media/Intranet-of-Things
            src: /dev/sda1
            fstype: ntfs
            opts: noatime
            state: mounted