---
- hosts: all
  become: true

  tasks:
    - name: Add docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: 'o+x'
        force: true

    - name: Add docker repo
      ansible.builtin.apt_repository:
        filename: docker
        repo: 'deb [arch=arm64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu   kinetic stable'

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - net-tools
          - curl
          - docker-ce
          - docker-ce-cli
        state: latest
        update_cache: true

    - name: Install docker and docker-compose Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Ensure docker deamon is running
      service:
        name: docker
        state: started
      become: true